import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {Button, Card, CardGroup, Col, Container, Row, Image} from 'react-bootstrap'
import ExpendableText from "@/components/shared/ExpendableText";
import React from "react";


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Hack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <CardGroup className={styles.homePage}>
                <div>
                    <CardGroup className={styles.startImg}>
                        <Card>
                            <Image
                                src={
                                    'https://firebasestorage.googleapis.com/v0/b/female-period-support.appspot.com/o/two_hands.jpg?alt=media&token=71be8f67-6d51-41d4-8f74-e5fc08aeabc6'
                                }
                                width={'100%'}
                                height={970}/>
                        </Card>
                    </CardGroup>
                </div>
                <div>
                    <CardGroup className={styles.ourMission}>
                        <Card className={styles.txtGroup}>
                            <Card.Title className={styles.missionTitle}>Our Mission</Card.Title>
                            <Card.Text className={styles.missionText}>Providing a safe and supportive platform for advocating and supporting homeless women who struggle to access menstrual products.</Card.Text>
                        </Card>
                    </CardGroup>
                </div>
                {/*<div className="container">*/}
                {/*    <CardGroup className={styles.getInvolved}>*/}
                {/*        <h1>Get Involved</h1>*/}
                {/*    </CardGroup>*/}
                {/*    <div>*/}

                {/*        <div style={{ display: "flex" , padding: "2em"}} >*/}

                {/*            <div className ="col-7 align-content-center">*/}
                {/*                <Card style={{ width: '35rem' }}>*/}
                {/*                    <Card.Img className = "card_image"*/}
                {/*                              variant="top"*/}
                {/*                              src="https://firebasestorage.googleapis.com/v0/b/female-period-support.appspot.com/o/HelpingWomenPeriod_Logo.png?alt=media&token=65ae556b-eeee-45fa-9b28-98c0a6c6d764"/>*/}
                {/*                    <Card.Body>*/}
                {/*                        <Card.Title>Helping Women Period</Card.Title>*/}
                {/*                        <ExpendableText maxHeight={70}>*/}
                {/*                            HWP prioritizes the needs of people experiencing relationship violence,*/}
                {/*                            who have been denied access to resources due to systemic racism and institutional biases,*/}
                {/*                            we direct support to communities of color and organizations that serve BIPOC communities.*/}
                {/*                            We listen to our BIPOC partners and we adjust our support based on the cultural and traditional preferences of the people we serve.*/}
                {/*                        </ExpendableText>*/}
                {/*                        <div className="col text-center">*/}
                {/*                            <Button href="https://www.helpingwomenperiod.org/make-a-donation/" variant="primary" size="lg" style = {{background: '#A52A2A', width: '200px'}} >Donate</Button>*/}
                {/*                        </div>*/}
                {/*                    </Card.Body>*/}
                {/*                </Card>*/}
                {/*            </div>*/}
                {/*            <div className ="col-7 align-content-center">*/}
                {/*                <Card style={{ width: '35rem' }}>*/}
                {/*                    <Card.Img className = "card_image"*/}
                {/*                              variant="top"*/}
                {/*                              src="https://firebasestorage.googleapis.com/v0/b/female-period-support.appspot.com/o/PeriodProject_Logo.png?alt=media&token=193717d8-900a-4d92-8057-321a7fc99bfb" />*/}
                {/*                    <Card.Body>*/}
                {/*                        <Card.Title>The Period Project</Card.Title>*/}
                {/*                        <ExpendableText maxHeight={70}>*/}
                {/*                            At The Period Project, we're improving the lives of menstruators one period at a time.*/}
                {/*                            By increasing local, national, and global awareness of period poverty and delivering menstrual hygiene products to those in need,*/}
                {/*                            we're replacing poverty with community and shame with dignity.*/}
                {/*                            We are part of a worldwide movement of similarly focused nonprofit organizations accelerating the momentum*/}
                {/*                            by incubating ideas and exchanging mutual aid for the common and greater good.*/}
                {/*                        </ExpendableText>*/}
                {/*                        <div className="col text-center">*/}
                {/*                            <Button href="https://periodproject.org/pages/donate" variant="primary" size="lg" style = {{background: '#A52A2A', width: '200px'}}>Donate</Button>*/}
                {/*                        </div>*/}
                {/*                    </Card.Body>*/}
                {/*                </Card>*/}
                {/*            </div>*/}
                {/*        </div>*/}

                {/*    </div>*/}
                {/*</div>*/}
                <div>
                    <CardGroup className={styles.startImg}>
                        <Card>
                            <Image
                                src={
                                    'https://firebasestorage.googleapis.com/v0/b/female-period-support.appspot.com/o/handinhand.jpg?alt=media&token=c60b9eef-eadb-4cb7-984f-dea20beb9eae'
                                }
                                alt="starter"
                                width={'100%'}
                                height={300}/>
                        </Card>
                    </CardGroup>
                </div>
                <div>
                    <CardGroup className={styles.ourGoals}>
                        <Card className={styles.txtGroup}>
                            <Card.Title className={styles.goalTitle}>Our Goal</Card.Title>
                            <Card.Text className={styles.goalText}>Our goal is to raise awareness about the issues surrounding menstrual hygiene for homeless women
                            </Card.Text>
                            <Card.Text className={styles.goalText}>and provide a platform for people to donate and support the cause.
                            </Card.Text>
                        </Card>
                    </CardGroup>
                </div>
            </CardGroup>

    </>
  )
}

export default Home;