import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Card, CardGroup, Container } from 'react-bootstrap'

const Involved: NextPage = () => {


    return (
        <>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
                <Container className={styles.involvedContainer}>
                </Container> 
        </>
    )
}

export default Involved;