import type { NextPage } from 'next'
import Head from 'next/head'
import React from "react";

const Resource: NextPage = () => {

    return (
        <>
            <Head>
                <title>Resource</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
    <div className="App">
   
    </div>
    </>
)
}

export default Resource;