import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { CardGroup } from 'react-bootstrap'

const Story: NextPage = () => {


    return (
        <>
            <Head>
                <title>Story</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <CardGroup className={styles.homePage}>

                    <h1>It is Story page</h1>
                </CardGroup>
            </div>
        </>
)
}

export default Story;